substitutions:
  _IMAGE: 'gcr.io/whiteblock/geth'
  _DIR: 'ethereum/geth'
timeout: '20m'
steps:
# build final docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', '$_IMAGE:$BRANCH_NAME',
            '-t', '$_IMAGE:$COMMIT_SHA',
            '.'
        ]
  dir: '$_DIR'
# push docker image tag(s) one branch, one immutable
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:$COMMIT_SHA' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:$BRANCH_NAME' ]
options:
  machineType: 'N1_HIGHCPU_32'
images: ['$_IMAGE:$BRANCH_NAME', '$_IMAGE:$COMMIT_SHA']
