substitutions:
  _IMAGE: 'gcr.io/whiteblock/base'
  _DIR: 'base/ubuntu1804'
timeout: '90m'
steps:
# allow these steps to fail, they try to pull cache first
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull $_IMAGE:ubuntu1804 || true' ]
# build final docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', '$_IMAGE:ubuntu18.04',
            '-t', '$_IMAGE:ubuntu1804',
            '--cache-from', '$_IMAGE:ubuntu1804',
            '.'
        ]
  dir: '$_DIR'
# push docker image tag(s) one branch, one immutable
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:ubuntu18.04' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:ubuntu1804' ]
options:
  machineType: 'N1_HIGHCPU_8'
images: ['$_IMAGE:ubuntu18.04','$_IMAGE:ubuntu1804']